name: console_cmd
description: A library include i/o tools to build cmd application efficiently
version: 1.0.5
homepage: https://github.com/CimZzz/console_cmd

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.10.1
  pedantic: ^1.9.2
  test: ^1.6.0
